name: build

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 glew
      - name: build pixie
        run: |
          cd .runtime
          clang ..\source\main.c -lSDL2 -lGLEW -framework OpenGL
