name: build

on: [push, pull_request]

jobs:
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build pixie
        run: |
          cd runtime
          cl ../source/main.c
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 glew
      - name: build pixie
        run: |
          cd runtime
          clang ../source/main.c -lSDL2 -lGLEW -framework OpenGL
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
          sudo apt-get install -qq libglew-dev
      - name: build pixie
        run: |
          cd runtime
          gcc ../source/main.c -lSDL2 -lGLEW -lGL -lm -pthread
